### ISSUE TITLE
Option overwrite = false

### ISSUE THREAD

**Issue by Shamballa** [NathanaelA/nativescript-themes#1]
Great plugin for changing themes!

My app is with nativescript and angular2. I have a folder for the different theme files. 
I want to use the global app.css and one of the theme files of choise. 
nativescript-themes overwrites app.css. Therefore I added a new option  in my forked version and set options.overwrite = false
I am not an expert in GitHub, but I think that you can see the changes in my forked version.
`                if (!(options && options.overwrite)) {
                    applicationCss = application.addCss(textCSS);
                } else {
                    applicationCss = application.parseCss(textCSS, cssFileName);
                }  `

**Comment by NathanaelA** [comment]
Yeah, it is designed to overwrite the CSS; the reason why is because we only want the current rules in memory.    If I had say a dark theme, and so I changed the font-color to white; but in the red theme I didn't change the font color; then when you applied the red them over the dark theme your dark theme color rule would still be in effect.    So the CSS needs to be cleared for theming to work properly.

Now as to your specific issue;  I assume you are not sure if you are aware but if you need common app.css to be included in your themes you can do `@import "app.css"` at the top of your theme css files and it will import those rules first.  :-)
